name: Update Ockam Elixir Dependency
description: Update Ockam Elixir Dependency

inputs:
  dependency_to_update: 
    description: "Dependency To Update"
    required: true
  ockam_ref:
    description: "Ockam Ref That Made The Update"
    required: true
  working_directory:
    description: "Working Directory Of Dependency"
    required: false

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      with:
        fetch-depth: 0

    - shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -ex
        git pull --rebase

        # Get all dependencies 
        mix local.hex --force
        mix local.rebar --force
        mix deps.get

        # Update deps
        mix deps.update ${{ inputs.dependency_to_update }}
        # Compile repository
        mix compile

    - shell: bash
      working-directory: ${{ inputs.working_directory }}
      run: |
        set -ex
        git pull --rebase --autostash
        git add mix.lock
        git commit -S -m "Update dependencies"

        git push
