name: Sign Image Workflow
description: Sign A Docker Image

inputs:
  cosign_private_key:
    description: "Cosign Private key"
    required: true
  cosign_password:
    description: "Cosign password"
    required: true
  image:
    description: "Docker image"
    required: true
  ref:
    description: "Commit ref that docker image was built on"
    required: true

runs:
  using: "composite"
  steps:
    - uses: sigstore/cosign-installer@536b37ec5d5b543420bdfd9b744c5965bd4d8730

    - shell: bash
      env:
        PRIVATE_KEY: '${{ inputs.cosign_private_key }}'
        COSIGN_PASSWORD: '${{ inputs.cosign_password }}'
      run: |
        if  cosign sign --key env://PRIVATE_KEY ${{ inputs.image }} -a "org=build-trust" -a "ref=${{ inputs.ref }}"; then
          echo "Signature verified"
        else
          echo "Invalid signature"
          exit 1
        fi
