name: Get Docker Image Digest
description: Get Docker Image Digest
inputs:
  image_name:
    description: "Image name"
    required: true
  buildx_metadata_file:
    description: "Buildx metadata if multi platform build is used"
    required: false
outputs:
  image_digest:
    description: "Image digest"
    value: ${{ steps.image_digest.outputs.digest }}

runs:
  using: "composite"
  steps:
    - shell: bash
      id: image_digest
      run: |
        set -ex
        metadata_file="${{ inputs.buildx_metadata_file }}"

        if [[ -z $metadata_file ]]; then
          image_details=$(docker image inspect ${{ inputs.image_name }})
          digest=$(jq -r .[0].RepoDigests[0] <<<$image_details)
          digest=${digest#*@}
        else
          digest=$( jq -r '."containerimage.digest"' $metadata_file )
        fi

        echo "digest=$digest" >> $GITHUB_OUTPUT
