name: Delete Workflow Run In A Repository
description: Delete Workflow Run In A Repository

inputs:
  github_token:
    description: "GitHub Token"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      id: runner
      run: |
        set -ex

        workflow_id=""

        workflow_file="${{ github.event.workflow }}"

        repository_workflows=$(gh api \
          -H "Accept: application/vnd.github+json" \
          /repos/${{ github.repository }}/actions/workflows)

        workflow_len=$(jq '.workflows | length' <<< $repository_workflows)

        for (( c=0; c<$workflow_len; c++ )); do
          file_path=$(jq -r ".workflows[${c}].path" <<< $repository_workflows)
          if [[ $file_path ==  $workflow_file ]]; then
            workflow_id=$(jq -r ".workflows[${c}].id" <<< $repository_workflows)
            break
          fi
        done

        echo "Workflow ID is $workflow_id"

        cancelled_run_ids=$(gh api \
          -X GET  -H "Accept: application/vnd.github+json" -f status=cancelled -f per_page=30  \
          /repos/${{ github.repository }}/actions/workflows/${workflow_id}/runs | jq '.workflow_runs[].id')

        if [[ $cancelled_run_ids == 'null' ]]; then
          exit 0
        fi

        for run_id in ${cancelled_run_ids[@]}; do
          job_details=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/runs/${run_id}/jobs | jq '.jobs')

          job_details_len=$(jq '. | length' <<< $job_details)

          if [[ $job_details_len < 1 ]]; then
            echo "Job length is invalid, deleting anyway"
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/actions/runs/${run_id}

            continue
          fi

          first_job_conclusion=$(jq -r '.[0].conclusion' <<< $job_details)

          if [[ $first_job_conclusion == 'cancelled' ]]; then
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/actions/runs/${run_id}
          fi
        done
