name: Delete Workflow Run
description: Delete Workflow Run. Normally Called On Cancelled Workflows

inputs:
  github_token:
    description: "GitHub Token"
    required: true
  script_name:
    description: "Script Name To Run As Post Job"
    required: false
    default: delete_workflow_run.sh

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -ex

        echo "
          set -ex && curl \
            -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ inputs.github_token }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
        " > /${{ inputs.script_name }}

        chmod +x /${{ inputs.script_name }}
        /${{ inputs.script_name }}
