name: Delete Workflow Run
description: Delete Workflow Run. Normally Called On Cancelled Workflows

inputs:
  github_token:
    description: "GitHub Token"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        set -ex

        curl \
          -X DELETE \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ inputs.github_token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}
