name: Delete Repository Workflow Run
description: Delete Repository Workflow Run

inputs:
  github_token:
    description: "GitHub Token"
    required: true

runs:
  using: composite
  steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}
      id: runner
      run: |
        set -ex

        cancelled_run_ids=$(gh api \
          -X GET  -H "Accept: application/vnd.github+json" -f status=cancelled -f per_page=40  \
          /repos/${{ github.repository }}/actions/runs | jq '.workflow_runs[].id')

        if [[ $cancelled_run_ids == 'null' ]]; then
          exit 0
        fi

        for run_id in ${cancelled_run_ids[@]}; do
          job_details=$(gh api \
            -H "Accept: application/vnd.github+json" \
            /repos/${{ github.repository }}/actions/runs/${run_id}/jobs | jq '.jobs')

          job_details_len=$(jq '. | length' <<< $job_details)

          if [[ $job_details_len < 1 ]]; then
            echo "Job length is invalid, deleting anyway"
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/actions/runs/${run_id}

            continue
          fi

          first_job_conclusion=$(jq -r '.[0].conclusion' <<< $job_details)

          if [[ $first_job_conclusion == 'cancelled' ]]; then
            gh api \
              --method DELETE \
              -H "Accept: application/vnd.github+json" \
              /repos/${{ github.repository }}/actions/runs/${run_id}
          fi
        done
